### PR TITLE
Use standard pathes for libs

### PR DESCRIPTION
**Pull request by joergboe**

### CODE REVIEW

**Comment by ddebrunner** [comment]
Not specific to this pull request but it seems strange that the **generated** xml operator model files are checked into git.

The need to build into a "non-standard" location seems somewhat suspicious as well.

**Comment by joergboe** [comment]
1. The checked in xml files are in fact not generated because there is no annotation PrimitiveOperator.
Only one operator has the annotation 'SparkCollaborativeFilteringALS'
2. use a non-standard place for the class files to avoid that the class files are put into the sab file. (impl/java/bin is pulled into sab automatically)
The jar lib is placed at a standard place (lib) and pulled per default into sab.

**Comment by ddebrunner** [comment]
> impl/java/bin is pulled into sab automatically

and that was handled by an exclude in the info.xml.

**Comment by joergboe** [comment]
yes,
but to use a different directory seems to be simpler than to add a sab-section in the info.xml file

**Comment by joergboe** [comment]
But if the class files are in impl/java/bin you will see this alerts:
Class com.ibm.streamsx.sparkmllib.collaborativefiltering.SparkCollaborativeFilteringALS in file lib/streams-sparkmllib.jar was skipped: a class with the same name in file impl/java/bin/com/ibm/streamsx/sparkmllib/collaborativefiltering/SparkCollaborativeFilteringALS$StreamsModel.class was already processed.

**Pull request merged**
